feat: diamond pepe gen 2 mint (DOP-178)
dopex-io/elvarg pull request #202
Opened 2022-05-11 09:22 UTC by hellodespereaux

2023-02-02 16:30 UTC, hellodespereaux commented
I migrated almost all files to styled, will ping again once I finish

2023-02-02 16:30 UTC, hellodespereaux commented on src/pages/nfts/duel/index.tsx
> +import styles from 'components/nfts/duel/styles.module.scss';
done

2023-02-02 16:30 UTC, hellodespereaux commented on src/pages/nfts/diamondpepes/index.tsx
> +import styles from 'components/nfts/diamondpepes/styles.module.scss';
done

2023-02-02 16:30 UTC, hellodespereaux commented on src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +import styles from './styles.module.scss';
done

2023-02-02 16:30 UTC, hellodespereaux commented on src/components/nfts/duel/Duels/index.tsx
> +import styles from '../styles.module.scss';
done

2023-02-02 16:31 UTC, hellodespereaux commented on src/components/nfts/duel/styles.module.scss
> +    url('/images/nfts/pepes/duel-pepe-bg.png');
how to do it for images within css rules?

2023-02-02 16:31 UTC, hellodespereaux commented on src/components/nfts/diamondpepes/ActionsDialog/styles.module.scss
> +}
done

2023-02-06 13:53 UTC, hibou-de-nuit requested changes

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/diamondpepes/ActionsDialog/index.tsx
>  import { useEffect, useState, useMemo, useCallback } from 'react';
we don't need diamondpepes/ folder since it contains only diamondpepes/ActionsDialog, move it into nfts/components/Dialogs or a more suitable place @hellodespereaux

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
Organize import

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +                </Box>
Repeating components. Make it reusable

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +              </Box>
make all repeating components into reusable ones

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
Break this component down into smaller ones. 
- Use re-usable components where there are repeating html
- Move state related code into store
- Make <Moves /> component it's own component instead of a memoized callback here (line 329)

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +              will lose all my funds{' '}
All texts/descriptions that are not mutated can be stored in a json file and imported here. It'll clean up this component

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +
remove empty lines between html

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +
remove empty lines between html

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +
few more places with empty lines. remove all of them

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
Reduce component size. Apply the same points in CreateDuel.tsx here too

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
Reduce component size

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +
remove empty lines

2023-02-06 13:53 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +                      </TableCell>
change into reusable component. variants, classnames and fonts are the same

2023-02-06 13:58 UTC, hibou-de-nuit commented on src/components/nfts/duel/styles.module.scss
> +    url('/images/nfts/pepes/duel-pepe-bg.png');
it's fine, we can omit Next/Image for background images. Minify if you can, and load the bg using tailwindcss as we did with the vaults previously

2023-02-06 14:01 UTC, hibou-de-nuit commented on apps/dapp/src/pages/nfts/duel/index.tsx
> +        </Box> */}
Remove this

2023-02-07 14:54 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/diamondpepes/ActionsDialog/index.tsx
>  import { useEffect, useState, useMemo, useCallback } from 'react';
done

2023-02-07 14:54 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
done

2023-02-07 15:04 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +                </Box>
done

2023-02-07 15:28 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +              </Box>
done

2023-02-07 15:29 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
done

2023-02-07 15:29 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +              will lose all my funds{' '}
Where are we doing this so I can copy the structure?

2023-02-07 15:30 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +
done

2023-02-07 15:32 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/CreateDuel.tsx
> +
done

2023-02-07 15:32 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
done

2023-02-07 15:35 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +import React, { useState, useMemo, useCallback, useEffect } from 'react';
done

2023-02-07 15:37 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +
done

2023-02-07 15:42 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +                      </TableCell>
done

2023-02-07 15:42 UTC, hellodespereaux commented on apps/dapp/src/pages/nfts/duel/index.tsx
> +        </Box> */}
done

2023-02-14 18:47 UTC, hibou-de-nuit approved these changes

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +                        </Typography>
use SimpleText here too. pass the span as a ReactNode prop and rename the prop label to something more meaningful like 'content'

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +                    </Box>
repeating html to common component

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
empty line

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
empty line

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
empty line

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
more places with empty lines

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +
empty lines on this file

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +
empty lines

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/pages/nfts/diamondpepes/index.tsx
> +
empty lines

2023-02-14 18:47 UTC, hibou-de-nuit commented on apps/dapp/src/pages/nfts/duel/index.tsx
> +
remove empty lines between html tags

2023-02-15 13:55 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Duels/index.tsx
> +                        </Typography>
done

2023-02-15 14:02 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +                    </Box>
done

2023-02-15 14:02 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
fixed

2023-02-15 14:03 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
done

2023-02-15 14:03 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/FindDuel.tsx
> +
done

2023-02-15 14:06 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +
done

2023-02-15 14:06 UTC, hellodespereaux commented on apps/dapp/src/components/nfts/duel/Dialogs/RevealDuel.tsx
> +
done

2023-02-15 14:07 UTC, hellodespereaux commented on apps/dapp/src/pages/nfts/diamondpepes/index.tsx
> +
done

2023-02-15 14:09 UTC, hellodespereaux commented on apps/dapp/src/pages/nfts/duel/index.tsx
> +
done

2023-03-31 18:45 UTC, merged