feat/olp index page
dopex-io/elvarg pull request #420
Opened 2023-02-04 04:53 UTC by garyunwin42

- feat: table
- feat: table header
- feat: feature assets
- feat: utili % and refactor
- refactor: featured

2023-02-09 14:43 UTC, hibou-de-nuit requested changes

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/index.tsx
> +import { IOlpApi } from '../../../pages/olp';
absolute paths are more readable

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/index.tsx
> +    if (!expiries || expiries === undefined) return [];
repeated falsy check

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/index.tsx
> +              </StyleTableCell>
StyledTableCell has the same children html, can be made into a re-usable component

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/pages/olp/index.tsx
> +import { OlpHome } from '../../components/olp/OlpHome';
organize external package import, use absolute path for OlpHome

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/pages/olp/index.tsx
> +            variant=""
remove empty variant from UI/Typography, use <span> if custom sizing is absolutely necessary

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/pages/olp/index.tsx
> +              <div className="flex flex-row">
flex is by default row flow. just "flex" is enough

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/pages/olp/index.tsx
> +                <ArrowForwardIcon
use tailwindcss. className="fill-current text-wave-blue" avoid sx prop if possible

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +export const FeaturedAsset = ({ olp }: { olp: IOlpApi | undefined }) => {
make this component clickable since it's highlighted on hover

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/index.tsx
> +              <SsovFilter
The arrow icon is mooshed into 'Network' in the UI

2023-02-09 14:43 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            className="w-6 h-6 "
- the arbitrum logo looks stretched
- removing trailing space

2023-02-09 14:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            className="w-6 h-6 "
The SSOVFilter component isn't working as expected for Expiry (can't deselect the filter) and Network (the list disappears if I selected arbitrum) dropdowns.

2023-02-09 14:50 UTC, garyunwin42 commented on apps/dapp/src/pages/olp/index.tsx
> +            variant=""
that's what the figma design looks like

2023-02-09 14:51 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            className="w-6 h-6 "
Will it be required to update the Featured Asset const in the code whenever there's a new featured vault?

2023-02-09 15:05 UTC, hibou-de-nuit commented on apps/dapp/src/pages/olp/index.tsx
> +            variant=""
it wasn't a comment on the appearance of the text. use span if there's no Figma typography variant for these types of headers

2023-02-10 02:24 UTC, garyunwin42 commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            className="w-6 h-6 "
- not sure about arb logo, it's the same code everywhere else
- dont think so. seems like the consensus is to have it hard-coded

2023-02-10 16:19 UTC, hibou-de-nuit approved these changes
Minor points, LGTM otherwise

2023-02-10 16:19 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +  console.log('utilizationData: ', utilizationData); // TODO: remove
remove console.log

2023-02-10 16:19 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +
remove whitespaces between html tags

2023-02-10 16:19 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/index.tsx
> +
remove empty lines

2023-02-10 16:19 UTC, hibou-de-nuit commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            dot={false}
suggestion: blur the lines if it's using hardcoded data. className="blur-sm"

2023-02-11 02:03 UTC, witherblock requested changes

2023-02-11 02:03 UTC, witherblock commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +    </>
Don't need to wrap this in a react fragment

2023-02-11 02:03 UTC, witherblock commented on apps/dapp/src/components/olp/OlpHome/AssetTableRow.tsx
> +          />
Sizing for arbitrum is off since the arbitrum does not have a square aspect ratio.

Using "w-6 h-auto" should fix this issue

2023-02-11 02:03 UTC, witherblock commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +            className="w-6 h-6 "
Sizing for arbitrum is off since the arbitrum logo does not have a square aspect ratio.

Using "w-6 h-auto" should fix this issue

2023-02-11 02:07 UTC, witherblock commented on apps/dapp/src/components/olp/OlpHome/FeaturedAsset.tsx
> +export const FeaturedAsset = ({ olp }: { olp: IOlpApi | undefined }) => {
FeaturedAsset is also not an appropriate name, same reason - https://github.com/dopex-io/elvarg/pull/420/files#r1103476509

2023-02-17 00:43 UTC, witherblock approved these changes

2023-02-17 00:43 UTC, merged