feat/DOP 47/ui tabs
dopex-io/elvarg pull request #427
Opened 2023-02-09 05:27 UTC by garyunwin42

- feat: add dopex ui package
- feat: tabs
- feat: disabled and icons
- chore: remove scrollable

2023-02-21 18:45 UTC, witherblock commented
@garyunwin42 any updates on this?

2023-02-22 01:50 UTC, garyunwin42 commented
> @garyunwin42 any updates on this?

fixed. thanks!

2023-02-26 22:41 UTC, witherblock requested changes
No export in index file

2023-02-26 23:13 UTC, witherblock requested changes

2023-02-26 23:13 UTC, witherblock commented on packages/ui/src/Tabs.tsx
> +}
Define this component like the above one, separate type and big arrow function and props broken down in the function

2023-02-27 01:03 UTC, witherblock approved these changes

2023-02-27 01:03 UTC, merged