feat(components): text field input (DOP-36)
dopex-io/elvarg pull request #435
Opened 2023-02-15 19:07 UTC by hibou-de-nuit

2023-03-20 14:12 UTC, witherblock requested changes

2023-03-20 14:12 UTC, witherblock commented on packages/ui/src/Input.tsx
> +}
extend HTML input props?

2023-03-20 15:10 UTC, hibou-de-nuit commented on packages/ui/src/Input.tsx
> +}
updated

2023-03-22 11:00 UTC, witherblock approved these changes

2023-03-22 11:00 UTC, merged