feat: option scalps
dopex-io/elvarg pull request #454
Opened 2023-03-06 17:05 UTC by Aercwarden

2023-03-24 08:12 UTC, witherblock requested changes

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/MenuItems.tsx
>  import { Menu } from "@headlessui/react";
Why change formatting for file?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/Tab.tsx
Why change formatting for file?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/CheckedIcon.tsx
> +import React, {  SVGProps } from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/ContentCopyIcon.tsx
> +import React, {  SVGProps } from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/DropdownArrowIcon.tsx
> +import React, {  SVGProps } from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/InsuredPerpsIcon.tsx
> +import React, {  SVGProps } from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/LongStraddleIcon.tsx
>      <path d="M10 11.539 8.846 8.462h2.308L10 11.539Z" fill="#FF617D" />
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/src/icons/PegHedgeIcon.tsx
> +    <path d="M10 5.385A4.614 4.614 0 0 0 5.385 10 4.614 4.614 0 0 0 10 14.615 4.614 4.614 0 0 0 14.615 10 4.614 4.614 0 0 0 10 5.385Z" fill="#C3F8FF" />
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/stories/Menu.stories.tsx
> +import React from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/stories/MenuItems.stories.tsx
> +import React from "react";
Why change formatting?

2023-03-24 08:12 UTC, witherblock commented on packages/ui/stories/Tab.stories.tsx
> +import {  ComponentMeta } from "@storybook/react";
Why change formatting?

2023-03-30 18:41 UTC, witherblock requested changes

2023-03-30 18:41 UTC, witherblock commented on apps/dapp/public/images/tokens/arb.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="470.287" height="514.251"><path fill="#2D374B" d="m291.134 237.469 35.654-60.5 96.103 149.684.046 28.727-.313-197.672a14.893 14.893
Unoptimized

2023-03-30 18:41 UTC, witherblock commented on apps/dapp/src/components/common/DexScreenerChart/index.tsx
> +});
Add TODO fix

2023-03-30 18:41 UTC, witherblock commented on apps/dapp/src/components/common/TradingViewChart/index.tsx
> +});
Add TODO fix

2023-03-31 13:06 UTC, hellodespereaux approved these changes

2023-03-31 13:09 UTC, merged