feat: zdte
dopex-io/elvarg pull request #457
Opened 2023-03-10 13:22 UTC by garyunwin42

2023-04-25 20:35 UTC, hibou-de-nuit requested changes

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/OptionsTable/OptionsTableRow.tsx
> +import { Typography } from 'components/UI';
Replace Typography with appropriate html tags (p, h1, h2, h3, h4, h5, h6; in special cases span & code)

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/OptionsTable/OptionsTableRow.tsx
> +      <Typography variant="h6" color="white">
Make these p tags.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/OptionsTable/index.tsx
> +    <Box className="flex flex-col flex-grow w-full whitespace-nowrap">
div

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/ClosedPositions/ClosedPositionsRow.tsx
> +          <Typography variant="h4" className="font-bold shadow-2xl">
replace Typography for titles with h1-6 tags

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/ClosedPositions/ClosedPositionsRow.tsx
> +        <Box className="flex justify-end">
replace box

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/OpenPositions/OpenPositionsRow.tsx
> +import { Box, IconButton, TableRow } from '@mui/material';
Remove Box and IconButton

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/OpenPositions/index.tsx
> +  Box,
Remove Box

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/index.tsx
> +import Button from '@mui/material/Button';
Use the UI package button

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Stats/index.tsx
> +interface StatsProps {}
Redundant interface

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Stats/index.tsx
> +const Stats: FC<StatsProps> = ({}) => {
Remove empty object prop

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Stats/index.tsx
> +    <>
No need for this react fragment.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/TopBar/index.tsx
> +      await updateUserZdtePurchaseData();
Promise.all()

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/ZdteDexScreenerChart/index.tsx
> +  // TODO: read from contract?
Any update required here? Remove otherwise

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/Zdte.ts
> +/* Autogenerated file. Do not edit manually. */
Delete this file

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/ZdteLP.ts
Delete this file.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/ZdtePositionMinter.ts
Delete.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/common.ts
Delete.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/factories/ZdteLP__factory.ts
Delete.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/mocks/factories/Zdte__factory.ts
Delete.

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/pages/zdte/[zdte].tsx
> +    <Box className="bg-black min-h-screen">
Box to div

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/store/Vault/zdte/index.ts
> +export const ZDTE: string = '0xd01e0ec59fb8cfbf64857de839e5c6e23c82511a';
fetch from sdk

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/store/Vault/zdte/index.ts
> +  setTextInputRef: async (ref: boolean) => {
Remove async

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/store/Vault/zdte/index.ts
> +  setSelectedSpreadPair: async (pair: ISpreadPair) => {
Remove async

2023-04-25 20:35 UTC, hibou-de-nuit commented on apps/dapp/src/store/Vault/zdte/index.ts
> +      // Addresses[42161].ZDTE[selectedPoolName],
Remove

2023-04-26 01:14 UTC, garyunwin42 commented on apps/dapp/src/components/zdte/Manage/DepositCard/index.tsx
> +    <Box className="flex justify-between p-2">
the dopex UI Input doesnt support handleChange that takes a param
```
Type '(e: {    target: {        value: React.SetStateAction<string | number>;    };}) => void' is not assignable to type 'ReactEventHandler'.
```

2023-04-26 01:23 UTC, garyunwin42 commented on apps/dapp/src/components/zdte/Manage/TradeCard/TradeButton.tsx
> +function canOpenPosition(
by whom? i've seen sources that recommend string literals
- https://brockherion.dev/blog/posts/enums-vs-typed-strings-in-typescript/, " I personally prefer using string literal types. To me, they’re simpler and have no footprint when compiled into JavaScript."
- https://www.reddit.com/r/javascript/comments/zsf541/avoid_using_enums_in_typescript/

2023-04-26 02:37 UTC, garyunwin42 commented on apps/dapp/src/components/zdte/Positions/OpenPositions/OpenPositionsRow.tsx
> +import { Box, IconButton, TableRow } from '@mui/material';
what should i replace `IconButton` with?

2023-04-26 13:37 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Manage/TradeCard/TradeButton.tsx
> +function canOpenPosition(
You're right, if Matt Pocock is against its usage, I can't refute. :)

2023-04-26 13:37 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Manage/DepositCard/index.tsx
> +    <Box className="flex justify-between p-2">
You can update the Input component in the UI package to handle this.

2023-04-27 13:36 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/TopBar/index.tsx
> +      await updateUserZdtePurchaseData();
note that if the updated states are dependent on each other, it's better to sequence them in .then(), otherwise this is fine.
```ts
updateStaticZdteData().then(() =>
    updateZdteData().then(() => 
        updateUserZdtePurchaseData()
    )
) // This assumes zdteData depends on staticZdteData, and purchaseData depends on zdteData
```

2023-04-27 13:41 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/OpenPositions/OpenPositionsRow.tsx
> +import { Box, IconButton, TableRow } from '@mui/material';
You can use an img tag with an event handler, but this is fine for now. Resolving

2023-04-28 01:22 UTC, garyunwin42 commented on apps/dapp/src/store/Vault/zdte/index.ts
> +      // Addresses[42161].ZDTE[selectedPoolName],
let's do this after we finalized the contract. there's still active deployment going on and making a change to sdk is too much effort.

2023-05-01 18:43 UTC, witherblock approved these changes

2023-05-01 18:54 UTC, witherblock approved these changes

2023-05-01 18:54 UTC, merged