fix: approve only desired amount
dopex-io/elvarg pull request #495
Opened 2023-04-15 23:16 UTC by Aercwarden

2023-04-20 19:47 UTC, witherblock requested changes

2023-04-20 19:47 UTC, witherblock commented on apps/dapp/src/components/ssov/DepositPanel/index.tsx
> +  );
Why do you need a different state variable for BN?

2023-04-22 05:31 UTC, Aercwarden commented on apps/dapp/src/components/ssov/DepositPanel/index.tsx
> +  );
When getUserReadableAmount is used precision is lost and then when user clicks max button, it inputs slightly higher amount than users balance, hence keeping track of the balance in bignumber solves this issue

2023-04-24 18:54 UTC, witherblock approved these changes

2023-04-24 18:54 UTC, merged