fix/zeros and loading
dopex-io/elvarg pull request #515
Opened 2023-05-11 03:28 UTC by garyunwin42

- fix: missing decimals
- fix: show loading

## Scope

[closes issue-###](https://link-to-your-issue)

## Implementation

With @pair

## Screenshots

|         | before | after |
| ------- | ------ | ----- |
| desktop |        |       |
| mobile  |        |       |

## How to Test

2023-05-13 11:47 UTC, hibou-de-nuit requested changes

2023-05-13 11:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Manage/DepositCard/index.tsx
> +    loadingAsset,
See if the setIsLoading function derived from the common slice performs the same purpose instead of creating setLoadingAsset

2023-05-13 11:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/ClosedPositions/ClosedPositionsRow.tsx
> +          </Typography>
Let's stick to html tags

2023-05-13 11:47 UTC, hibou-de-nuit commented on apps/dapp/src/components/zdte/Positions/OpenPositions/OpenPositionsRow.tsx
> +import { Typography } from 'components/UI';
Let's use simple html tags instead of mui and fix the share ui as well. Test the below snippet on other pages using share() as well.

```tsx
import { ReactNode, forwardRef } from 'react';

import { QRCodeSVG } from 'qrcode.react';

interface StatProps {
  name: string;
  value: string;
}

export interface ShareImageProps {
  title: ReactNode;
  percentage: number;
  customPath?: string;
  stats: StatProps[];
}

const Stat = ({ name, value }: StatProps) => {
  return (
    <div className="flex flex-col">
      <h5 className="font-bold text-white">{name}</h5>
      <h3 className="text-2xl font-mono font-bold shadow-2xl text-white">
        {value}
      </h3>
    </div>
  );
};

const ShareImage = (
  { title, percentage, stats, customPath = '/' }: ShareImageProps,
  ref: any
) => {
  return (
    <div
      className="bg-[url('/images/misc/share-bg.png')] h-[309px] bg-contain bg-no-repeat pt-20 px-9"
      ref={ref}
    >
      <div className="flex w-full justify-between">
        <div>
          <div className="text-white">{title}</div>
          <h1
            className={`font-mono font-bold text-[48px] ${
              percentage > 0 ? 'text-up-only' : 'text-down-bad'
            }`}
          >
            {percentage.toFixed(2)}%
          </h1>
        </div>
        <div className="self-end justify-end shadow-2xl mt-[-16px]">
          <QRCodeSVG value={`https://app.dopex.io${customPath}`} />
        </div>
      </div>
      <div className="grid grid-cols-3 mt-6">
        {stats.map((s) => {
          return <Stat key={s.name} {...s} />;
        })}
      </div>
    </div>
  );
};

export default forwardRef(ShareImage);
```

2023-05-13 11:47 UTC, hibou-de-nuit commented on apps/dapp/src/pages/zdte/[zdte].tsx
> +            updateVolumeFromSubgraph(),
why not merge updateUserZdtePurchaseData() and getUserPurchaseData() into a single function in the store so that they are not dependent on each other here? the only difference is livePnl and breakeven.

2023-05-13 11:49 UTC, hibou-de-nuit commented on apps/dapp/src/pages/zdte/[zdte].tsx
> +            updateVolumeFromSubgraph(),
getUserPurchaseData() is also semantically misleading. It's not a getter, it's implemented as a setter

2023-05-13 15:39 UTC, garyunwin42 commented on apps/dapp/src/pages/zdte/[zdte].tsx
> +            updateVolumeFromSubgraph(),
`userZdteOpenPositions` and `userZdteClosedPositions` both depend on `userZdteSpreadPositions`. tl;dr duplicate code.

2023-05-15 16:43 UTC, hibou-de-nuit approved these changes

2023-05-15 18:29 UTC, merged