feat. option scalps order type
dopex-io/elvarg pull request #549
Opened 2023-06-10 10:26 UTC by hellodespereaux

-->

## Scope

New feature implementation.

## Implementation

Scalps now support order limits using Uniswap V3 single side liquidity deposits.

## Screenshots

Not available

## How to Test

Open scalps page and trade

2023-06-12 04:28 UTC, witherblock requested changes

2023-06-12 04:28 UTC, witherblock commented on apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
> +import CustomButton from 'components/UI/Button';
Use Button from dopex-ui library

2023-06-12 04:28 UTC, witherblock commented on apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
> +    // @ts-ignore TODO: FIX
No ts ignores

2023-06-12 04:28 UTC, witherblock commented on apps/dapp/src/store/Vault/scalps/index.ts
> +const optionScalpsABI = [
ABI from sdk

2023-06-12 16:30 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
> +    // @ts-ignore TODO: FIX
done

2023-06-13 06:34 UTC, witherblock requested changes

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/DepositCard/index.tsx
>  import Input from '@mui/material/Input';
Use Input from @dopex-io/ui and use div instead of Box

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/Dialogs/Withdraw.tsx
>  import Button from '@mui/material/Button';
Use Button from @dopex-io/ui and use div instead of Box

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/Dialogs/Withdraw.tsx
>  import Typography from '@mui/material/Typography';
Use tailwind font classes instead of typography from mui

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
> +import Input from '@mui/material/Input';
Use Input from @dopex-io/ui

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/Orders/OrdersTable.tsx
> +import getUserReadableAmount from 'utils/contracts/getUserReadableAmount';
getUserReadableAmount is deprecated, use ethers utils to achieve the same thing.

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/Orders/OrdersTable.tsx
> +import formatAmount from 'utils/general/formatAmount';
import from util index files instead

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
>  import getUserReadableAmount from 'utils/contracts/getUserReadableAmount';
getUserReadableAmount is deprecated, use ethers utils to achieve the same thing.

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/TradeCard/index.tsx
>  import Input from '@mui/material/Input';
Use Input from @dopex-io/ui

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/VaultCard/index.tsx
>  import Box from '@mui/material/Box';
Use div

2023-06-13 06:34 UTC, witherblock commented on apps/dapp/src/components/scalps/VaultCard/index.tsx
>  import Typography from 'components/UI/Typography';
Typography is deprecated, use tailwind font classes instead

2023-06-13 16:54 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/DepositCard/index.tsx
>  import Input from '@mui/material/Input';
done everywhere

2023-06-13 16:54 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/Dialogs/Withdraw.tsx
>  import Button from '@mui/material/Button';
done

2023-06-13 16:55 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/Dialogs/Withdraw.tsx
>  import Typography from '@mui/material/Typography';
done everywhere

2023-06-13 16:59 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/LimitOrderPopover/index.tsx
> +import Input from '@mui/material/Input';
done

2023-06-13 17:05 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/VaultCard/index.tsx
>  import Typography from 'components/UI/Typography';
done

2023-06-13 17:05 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/TradeCard/index.tsx
>  import Input from '@mui/material/Input';
done

2023-06-13 17:06 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/Positions/PositionsTable.tsx
>  import getUserReadableAmount from 'utils/contracts/getUserReadableAmount';
done

2023-06-13 18:41 UTC, hellodespereaux commented on apps/dapp/src/components/scalps/Orders/OrdersTable.tsx
> +import formatAmount from 'utils/general/formatAmount';
done

2023-06-19 13:40 UTC, witherblock requested changes

2023-06-19 13:40 UTC, witherblock commented on apps/dapp/src/components/common/AppBar/NftClaims/NftClaimButton.tsx
> +export default NftClaimButton;
Why remove last line?

2023-06-19 13:40 UTC, witherblock commented on apps/dapp/src/components/common/AppBar/RdpxAirdropButton/index.tsx
> +export default RdpxAirdropButton;
Why remove last line?

2023-06-19 13:40 UTC, witherblock commented on apps/dapp/src/pages/scalps/[poolName].tsx
> +        <AppBar />
Use PageLayout

2023-06-19 13:40 UTC, witherblock commented on apps/dapp/src/pages/scalps/[poolName].tsx
> +  return <OptionScalps poolName={poolName} />;
Why remove seo tags?

2023-06-19 13:40 UTC, witherblock commented on packages/sdk/src/abis/OptionScalps.json
> +[
Not minified

2023-06-19 13:40 UTC, witherblock commented on packages/sdk/src/abis/OptionScalpsLimitOrderManager.json
> +      "type": "event"
Not minified

2023-06-19 17:19 UTC, hellodespereaux commented on apps/dapp/src/components/common/AppBar/NftClaims/NftClaimButton.tsx
> +export default NftClaimButton;
done

2023-06-19 17:19 UTC, hellodespereaux commented on apps/dapp/src/components/common/AppBar/RdpxAirdropButton/index.tsx
> +export default RdpxAirdropButton;
done

2023-06-19 17:22 UTC, hellodespereaux commented on apps/dapp/src/pages/scalps/[poolName].tsx
> +  return <OptionScalps poolName={poolName} />;
done

2023-06-19 17:24 UTC, hellodespereaux commented on apps/dapp/src/pages/scalps/[poolName].tsx
> +  return <OptionScalps poolName={poolName} />;
done

2023-06-19 17:24 UTC, hellodespereaux commented on apps/dapp/src/pages/scalps/[poolName].tsx
> +        <AppBar />
done

2023-06-19 17:24 UTC, hellodespereaux commented on packages/sdk/src/abis/OptionScalps.json
> +[
done

2023-06-19 17:41 UTC, hellodespereaux commented on packages/sdk/src/abis/OptionScalpsLimitOrderManager.json
> +      "type": "event"
done

2023-06-19 20:50 UTC, tztokchad approved these changes

2023-06-19 20:50 UTC, tztokchad approved these changes

2023-06-19 20:51 UTC, merged