feat: staking rewards information display (DOP-414)
dopex-io/elvarg pull request #559
Opened 2023-06-18 14:25 UTC by Aercwarden

## Scope

1. Display staking rewards for a support SSOV in the strikes table.
2. Hide "current incentives" if total incentives are zero for an SSOV or epoch.

## Implementation

Staking rewards related information called from store where contract calls are made, which are later pulled to components.

## Screenshots

![Screenshot 2023-06-18 at 6 24 21 PM](https://github.com/dopex-io/elvarg/assets/90272722/d9c39b39-bc5c-4125-8a37-8129574b2ddd)

![Screenshot 2023-06-18 at 6 24 48 PM](https://github.com/dopex-io/elvarg/assets/90272722/1084452b-1474-4321-9ed4-761910470626)

2023-06-19 13:21 UTC, witherblock requested changes

2023-06-19 13:21 UTC, witherblock commented on apps/dapp/src/components/ssov/DepositPanel/index.tsx
> +        });
Why did you change this?

2023-06-19 13:24 UTC, Aercwarden commented on apps/dapp/src/components/ssov/DepositPanel/index.tsx
> +        });
To update stats after handleStake is called, otherwise handleStake was call after state updates. updateSsovUserData() updates staking rewards related states.

2023-06-19 13:29 UTC, witherblock requested changes

2023-06-19 13:29 UTC, witherblock commented on apps/dapp/src/utils/options/parseOptionSymbol.ts
> +}
this is unnecessary and more confusing, the current option symbols in the contracts are a standard for all option instrument

2023-06-19 17:16 UTC, Aercwarden commented on apps/dapp/src/utils/options/parseOptionSymbol.ts
> +}
Should I let it be as it is? It would look atleast better without the hiphens

2023-06-21 13:21 UTC, witherblock approved these changes

2023-06-21 13:21 UTC, merged