feat/straddles settled positions
dopex-io/elvarg pull request #568
Opened 2023-06-19 17:21 UTC by garyunwin42

- refactor: prepend Open
- feat: add ClosePositions
- feat: button for open and closed
- feat: remove log

## Scope

[closes issue-###](https://link-to-your-issue)

## Implementation

With @pair

## Screenshots

|         | before | after |
| ------- | ------ | ----- |
| desktop |        |       |
| mobile  |        |       |

## How to Test

2023-06-20 22:05 UTC, garyunwin42 commented
Adding the hash below the title since it's too long to go into a column

2023-06-20 22:06 UTC, garyunwin42 commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +            <span className="text-sm inline-block break-all overflow-visible">
hash is too long to go into the column

2023-06-21 13:22 UTC, witherblock requested changes

2023-06-21 13:22 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +  Box,
No box usage

2023-06-21 13:23 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +            <span className="text-sm inline-block break-all overflow-visible">
use smartTrim

2023-06-21 16:24 UTC, witherblock requested changes

2023-06-21 16:24 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
>  import formatAmount from 'utils/general/formatAmount';
You can import both from the utils/general index file

2023-06-21 16:27 UTC, witherblock requested changes

2023-06-21 16:27 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +          },
I mean't adding tx hash in the table on in the share image

2023-06-21 16:27 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +  });
This will only get data for the arbitrum straddles, what about the polygon ones?

2023-06-21 16:27 UTC, witherblock commented on apps/dapp/src/components/straddles/Positions/ClosedPositions/ClosedPositionsTable.tsx
> +  });
https://api.thegraph.com/subgraphs/name/psytama/dopex-straddles-polygon

2023-06-22 11:18 UTC, witherblock approved these changes

2023-06-22 11:19 UTC, merged