feat/matic portfolio
dopex-io/elvarg pull request #601
Opened 2023-07-03 16:27 UTC by garyunwin42

- feat: portfolio in ssov
- feat: matic portfolio

## Scope

[closes issue-###](https://link-to-your-issue)

## Implementation

With @pair

## Screenshots

|         | before | after |
| ------- | ------ | ----- |
| desktop |        |       |
| mobile  |        |       |

## How to Test

2023-07-04 10:13 UTC, witherblock requested changes
Portfolio should fetch data for all chains not which chain the user is in.

Also update the template description of the PR correctly.

2023-07-06 15:59 UTC, hibou-de-nuit requested changes
The portfolio page is stuck in infinite loading for both chains. Besides that and some improvements, LGTM.

2023-07-06 15:59 UTC, hibou-de-nuit commented on apps/dapp/src/store/Portfolio/index.ts
> +      }),
Let's query based on chainId, add a mapping like this: 
```ts
const chainIdToQuery: Record<string | number, string> = {
   [chainId]: API_URL,
  ...
}
```

2023-07-06 15:59 UTC, hibou-de-nuit commented on apps/dapp/src/store/Portfolio/index.ts
> +      }),
cc. [here](https://github.com/dopex-io/elvarg/pull/601/files#diff-ca1754bc517e40750e49c2d67e0663d96f63b832b6ca3d528b3a446b6815b2e8R372), [here](https://github.com/dopex-io/elvarg/pull/601/files#diff-ca1754bc517e40750e49c2d67e0663d96f63b832b6ca3d528b3a446b6815b2e8R375), [here](https://github.com/dopex-io/elvarg/pull/601/files#diff-ca1754bc517e40750e49c2d67e0663d96f63b832b6ca3d528b3a446b6815b2e8R381), and several following lines querying both polygon as well as arbitrum.

2023-07-06 16:05 UTC, hibou-de-nuit commented on apps/dapp/src/store/Portfolio/index.ts
> +      }),
Noted witherblock's review. Please ignore.

2023-07-06 23:33 UTC, garyunwin42 commented
> The portfolio page is stuck in infinite loading for both chains. Besides that and some improvements, LGTM.

where are you seeing the infinite loading? it worked for me and here's the preview: https://dapp-git-feat-matic-portfolio-dopex-io.vercel.app/portfolio

2023-07-07 08:08 UTC, witherblock submitted a review, later dismissed
Fix PR description

2023-07-07 18:58 UTC, hibou-de-nuit commented
> > The portfolio page is stuck in infinite loading for both chains. Besides that and some improvements, LGTM.
> 
> where are you seeing the infinite loading? it worked for me and here's the preview: https://dapp-git-feat-matic-portfolio-dopex-io.vercel.app/portfolio

Same issue in the preview link. It is likely that the straddlesv2__factory is not accounted for in the portfolio

2023-07-09 13:17 UTC, hibou-de-nuit approved these changes
New changes LGTM. 

Some other issues were noted. 
- For a straddles deposit, the 'open' button takes us to a broken page. the URL param ```?epoch=###``` breaks the page and doesn't load contract data.
- When connected to Polygon chain, SSOV positions from the arb chain do not appear.

We're good to merge once these have been addressed.

2023-07-09 18:58 UTC, garyunwin42 commented on apps/dapp/src/store/Portfolio/index.ts
> +          vault.paused,
weird, it worked for me
<img width="798" alt="image" src="https://github.com/dopex-io/elvarg/assets/109383132/74d0bb80-76d7-40de-a414-df499a13d748">

2023-07-09 19:08 UTC, garyunwin42 commented on apps/dapp/src/store/Portfolio/index.ts
> +          vault.paused,
open from portfolio worked for me too... 😂 
<img width="662" alt="image" src="https://github.com/dopex-io/elvarg/assets/109383132/cf1d46a6-8d3c-42ee-89c9-bd1b35eee470">

2023-07-10 14:55 UTC, hibou-de-nuit commented on apps/dapp/src/store/Portfolio/index.ts
> +          vault.paused,
Oddly still seems to be the case for me. I switched to polygon chain on the portfolio, refreshed, and get the result below. 
![Screenshot 2023-07-10](https://github.com/dopex-io/elvarg/assets/85767768/a38566cb-06a4-4c0c-aacc-1820dbfb29bf)
![Screenshot 2023-07-10](https://github.com/dopex-io/elvarg/assets/85767768/c83c1d34-8374-4e36-bc0a-bc80973211e8)
![Screenshot 2023-07-10](https://github.com/dopex-io/elvarg/assets/85767768/4b5681c1-fe04-406b-8c9e-4d7cd6ce583c)

2023-07-10 17:21 UTC, garyunwin42 commented on apps/dapp/src/store/Portfolio/index.ts
> +          vault.paused,
what's your address? lemme try to reproduce with yours

2023-07-11 16:21 UTC, garyunwin42 commented on apps/dapp/src/store/Portfolio/index.ts
> +          vault.paused,
i refreshed but it worked for me
<img width="1095" alt="image" src="https://github.com/dopex-io/elvarg/assets/109383132/ecca3eec-b901-41ce-89a1-6ff16c2509f8">

2023-08-10 00:15 UTC, merged