Implement Notifi React Card
dopex-io/elvarg pull request #633
Opened 2023-07-25 18:02 UTC by marukohao

## Scope

Implement Notifi React Card

## Screenshots

![Untitled](https://github.com/dopex-io/elvarg/assets/26240001/e04ad502-6741-48bd-8b81-7c4c1f033c29)

## How to Test
 - connect wallet and set up the network to Arbitrum
 - you can see the react card modal shows up by clicking the bell icon in AppBar
 - follow the steps in the card for testing

2023-08-10 18:37 UTC, witherblock requested changes

2023-08-10 18:37 UTC, witherblock commented on apps/dapp/src/components/common/AppBar/index.tsx
> +import { Modal } from '@mui/material';
import the component directly: import Modal from "@mui/material/Modal";

2023-08-10 18:45 UTC, marukohao commented on apps/dapp/src/components/common/AppBar/index.tsx
> +import theme from 'style/muiTheme';
removed

2023-08-10 18:46 UTC, marukohao commented on apps/dapp/src/components/common/AppBar/index.tsx
> +import { Modal } from '@mui/material';
I have updated the import

2023-08-10 19:14 UTC, witherblock approved these changes

2023-08-17 17:10 UTC, witherblock approved these changes

2023-08-17 17:10 UTC, merged