feat: add Liquidity Used column to LPPositions
dopex-io/elvarg pull request #752
Opened 2023-11-15 09:09 UTC by hellodespereaux

## Scope

This PR adds the column Liquidity Used (%) to LPPositions

## How to Test

Open demo link and deposits some liquidity into CLAMM

2023-11-15 18:26 UTC, witherblock requested changes

2023-11-15 18:26 UTC, witherblock commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +import { BigNumber } from 'ethers';
We have migrated to viem, do not use ethers

2023-11-16 11:55 UTC, hellodespereaux commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +import { BigNumber } from 'ethers';
Sorry, it was a useless import as I then removed BigNumber
Pushed a commit to fix

2023-12-04 13:29 UTC, hellodespereaux commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +                100 - (100 * token1Withdrawable) / token1LiquidityInToken || 0,
done

2023-12-04 13:29 UTC, hellodespereaux commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +            <span className="text-stieglitz">{token1Symbol}</span>
done

2024-01-17 16:06 UTC, closed without merging