feat: show timestamp of initial deposit
dopex-io/elvarg pull request #829
Opened 2023-12-22 13:27 UTC by Aercwarden

![Screenshot 2023-12-22 at 5 26 57 PM](https://github.com/dopex-io/elvarg/assets/90272722/87ef8d72-88af-4aa7-96b6-dced669600e1)

2023-12-23 16:19 UTC, witherblock requested changes

2023-12-23 16:19 UTC, witherblock commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +        </div>
Why double nest with a span?

2023-12-23 16:53 UTC, Aercwarden commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/components/LPPositions.tsx
> +        </div>
refactored

2023-12-26 15:09 UTC, witherblock approved these changes

2023-12-26 15:09 UTC, merged