feat(clamm): UI features
dopex-io/elvarg pull request #835
Opened 2023-12-28 19:46 UTC by Aercwarden

2024-01-02 14:47 UTC, witherblock approved these changes

2024-01-02 14:47 UTC, witherblock commented
@hibou-de-nuit please review too

2024-01-04 15:27 UTC, hibou-de-nuit requested changes
UX Suggestion:
- Add labels next to the icons on the table for better clarity. It's a little obscure rn

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
> +  );
No need to memoize. The function causes rerender every time the params change.

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/columnHelpers/tradeHistory.tsx
> +                    'text-white',
Don't override like this, use ternary

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/PositionsTable/index.tsx
> +      <div className="w-full flex flex-row items-center">
flex-row is redundant

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/StrikesChain/components/FilterSettings/components/FilterSettingsButton/index.tsx
> +    </>
No need the fragment

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/StrikesChain/components/FilterSettings/components/RangeSelector/components/Slider/LiquidityThresholdInput/index.tsx
> +  const [type, setType] = useState(threshold[1] === 0 ? 'USD' : 'Options');
Client-side and server-side data mismatch errors could arise from setting default state like this.

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/StrikesChain/components/FilterSettings/components/RangeSelector/index.tsx
> +          </p>
reuse components

2024-01-04 15:27 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/StrikesChain/components/StrikesTable.tsx
> +        }
```tsx
filterSettings.liquidityThreshold[1] === 0 ? filterSettings.liquidityThreshold[0] < Number(liquidityAvailableUsd) : filterSettings.liquidityThreshold[0] < Number(optionsAvailable)
```

2024-01-04 16:23 UTC, Aercwarden commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/components/PositionSummary/index.tsx
> +      </div>
Not required, very specific to use case and won't be reused

2024-01-04 16:26 UTC, Aercwarden commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
> +  }, []);
it is used as dependency, hence as to be memoized

2024-01-04 16:26 UTC, Aercwarden commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
> +  );
has to change as per parameters

2024-01-04 16:31 UTC, Aercwarden commented on apps/dapp/src/components/clamm/StrikesChain/components/FilterSettings/components/RangeSelector/index.tsx
> +          </p>
used only once

2024-01-04 17:14 UTC, hibou-de-nuit commented on apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx
> +  }, []);
When ```key``` is changed, unselectPosition is recreated during rerender. This in turn updates the dependency array [here](https://github.com/dopex-io/elvarg/blob/1eb412c965a04c0016795267ff99bcc9cf0f1d51/apps/dapp/src/components/clamm/PositionsTable/components/Positions/BuyPositions/index.tsx#L65), which causes that handler to be recreated as well. So there isn't any memoization happening

2024-01-04 17:27 UTC, hibou-de-nuit approved these changes
Refer pending comments. LGTM

2024-01-04 18:52 UTC, merged